builds:
  - main: cmd/nem/main.go
    binary: nem
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip