language: go
sudo: false
os:
  - linux
  - osx
go:
  - 1.8
  - 1.9
  - tip
matrix:
  allow_failures:
    - go: tip
before_install:
  - make setup
script:
  - make build
  - make test
notifications:
  email:
    on_success: never
