language: go
sudo: false
os:
  - linux
  - osx
go:
  - 1.8
  - 1.9
  - release
install: make setup
script: make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
notifications:
  email: false
