version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/r8d8/nem-toolchain
    branches:
      only:
        - master
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
