version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/nem-toolchain/nem-toolchain
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
      - deploy:
          name: goreleaser
          command: |
            if [[ -n ${CIRCLE_TAG} ]]; then
              tempfile=$(mktemp)
              git log --pretty=oneline --abbrev-commit $(git describe --tags --abbrev=0)^.. |
                grep '^[^ ]* \[' |
                tee $tempfile
              curl -sL https://raw.githubusercontent.com/nem-toolchain/nem-toolchain/master/scripts/goreleaser |
                bash -s -- --release-notes $tempfile
            fi
deployment:
  trigger_tag:
    tag: /.*/
