version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/nem-toolchain/nem-toolchain
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
deployment:
  goreleaser:
    tag: /v\d+(\.\d+)*/
    commands: |
      if [[ ${CIRCLE_TAG} == v* ]]; then
        curl -sL https://git.io/goreleaser | bash -s -- --release-notes \
          <(git log --pretty=oneline --abbrev-commit $(git describe --tags --abbrev=0)^.. | grep '^[^ ]* \[')
      fi
