version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/nem-toolchain/nem-toolchain
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
      - deploy:
        name: Release
        command: |
          if [ -n "$CIRCLE_TAG" ]
          then
            curl -sL https://git.io/goreleaser | bash
          else
            echo "Not a release, skipping build"
          fi
