version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/nem-toolchain/nem-toolchain
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
      - deploy:
          name: goreleaser
          command: |
            if [[ -n ${CIRCLE_TAG} ]]; then
              curl -sL https://git.io/goreleaser |
                bash -s -- --debug --release-notes <(git log --pretty=oneline --abbrev-commit $(git describe --tags --abbrev=0)^.. | grep -v '^[^ ]* \(Fix\|Merge\|Update\)')
            fi
deployment:
  trigger_tag:
    tag: /.*/
