version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/nem-toolchain/nem-toolchain
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
      - deploy:
          name: goreleaser
          command: |
            echo "$CIRCLE_TAG"
            if [[ ${CIRCLE_TAG} == v* ]]; then
              echo "A test message" | tee RELEASE_NOTES
              curl -sL https://git.io/goreleaser | bash -s -- --release-notes=RELEASE_NOTES
            fi
deployment:
  trigger_tag:
    tag: /v\d+(\.\d+)*/
