version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)
      - deploy:
          name: goreleaser
          command: |
            echo "$CIRCLE_TAG"
            if [[ ${CIRCLE_TAG} == v* ]]; then
               curl -sL https://git.io/goreleaser | bash;
            fi
deployment:
  trigger_tag:
    tag: /v[0-9]+(\.[0-9]+)*(-.*)*/
