version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/r8d8/nem-toolchain
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)

  deployment:
    tag:
      tag: /v[0-9]+(\.[0-9]+)*(-.*)*/
      owner: user
      commands:
        - curl -sL https://git.io/goreleaser | bash