version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/nem-toolchain/nem-toolchain
    steps:
      - checkout
      - run: make setup
      - run: make ci
      - run: bash <(curl -s https://codecov.io/bash)

  deploy:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/r8d8/nem-toolchain
    enviroment:
      BUILD_DATE=$(date -u '+%Y/%m/%d %H:%M:%S')
      BUILD_VERSION=$(git describe --tags)
    steps:
      - checkout
      - run: mkdir -p dist
      - run: make setup
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              only: feature/init_deploy
